<?php

/**
 * Implementation of admin_plus_init().
 */
function admin_plus_init() {
  if (user_access('use admin toolbar') && admin_get_settings('layout') == 'horizontal_plus') {
    $path = drupal_get_path('module', 'admin_plus');
    drupal_add_js("{$path}/admin_plus.js");
    drupal_add_css("{$path}/admin_plus.css");
  }
}

/**
* Implementation of hook_menu().
*/
function admin_plus_menu(){
  $items = array();
  $items['test'] = array(
    'title' => 'Test',
    'page callback' => 'admin_plus_test',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function admin_plus_test() {
  if (!admin_suppress(FALSE) && $blocks = admin_get_admin_blocks()) {
    $position = admin_get_settings('position');
    $layout = admin_get_settings('layout');
    $behavior = admin_get_settings('behavior');
    $class = admin_get_settings('expanded') ? 'admin-expanded' : '';
    echo theme('admin_toolbar', $blocks, $position, $layout, $behavior);
  }
}

function admin_plus_form_admin_settings_form_alter (&$form, &$form_state) {
  $form['admin_toolbar']['layout']['#options']['horizontal_plus'] = t('Horizontal') .' plus';
}

/**
 * Implementation of hook_theme_registry_alter().
 */
function admin_plus_theme_registry_alter(&$theme_registry) {
  $theme_registry['admin_toolbar'] = $theme_registry['admin_plus_toolbar'];
}

function theme_admin_plus_toolbar ($blocks, $position, $layout, $behavior) {
  if (admin_get_settings('layout') == 'horizontal_plus') {
    return theme('admin_plus_toolbar_plus', $blocks, $position, $layout, $behavior);
  }
  return theme('admin_plus_toolbar_default', $blocks, $position, $layout, $behavior);
}
/**
 * Implementation of hook_theme().
 */
function admin_plus_theme($existing, $type, $theme, $path) {
  $items['admin_plus_toolbar_default'] = array(
    'arguments' => array(
      'blocks' => array(),
      'position' => 'ne',
      'layout' => 'horizontal',
      'behavior' => 'df',
    ),
    'template' => 'admin-toolbar',
    'path' => drupal_get_path('module', 'admin') . '/theme',
    'file' => 'theme.inc',
    'preprocess functions' => array('template_preprocess_admin_toolbar'),
  );
  $items['admin_plus_toolbar'] = array(
    'arguments' => array(
      'blocks' => array(),
      'position' => 'ne',
      'layout' => 'horizontal',
      'behavior' => 'df',
    ),
  );
  $items['admin_plus_toolbar_plus'] = array(
    'arguments' => array(
      'blocks' => array(),
      'position' => 'ne',
      'layout' => 'horizontal_plus',
      'behavior' => 'df',
    ),
    'template' => 'admin-plus-toolbar',
  );
  return $items;
}

/**
 * Preprocessor for theme('admin_plus_toolbar_plus').
 */
function template_preprocess_admin_plus_toolbar_plus(&$vars) {
  if (!empty($vars['blocks'])) {
    $items = array();
    foreach ($vars['blocks'] as $bid => $block) {
      $item = array();
      $item['data'] = '<span>'. $block->subject .'</span>';
      $item['data'] .= in_array($bid, array('admin-theme', 'admin-devel')) ?
      theme('item_list', array($block->content)) : $block->content;
      $item['class'] = $block->class;
      $item['id'] = 'admin-tab-'. $bid;
      $items[] = $item;
    }
    $vars['content'] = theme('item_list', $items);
  }
}